# Generated by Django 3.0.2 on 2020-04-03 12:45

from django.db import migrations, models
import todolist.models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_todo_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default='2020-04-03', validators=[todolist.models.ToDo.validate_date]),
        ),
    ]
